# Generated by Django 5.0.6 on 2024-06-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='option_3',
            new_name='option_four',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option_1',
            new_name='option_one',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option_4',
            new_name='option_three',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option_2',
            new_name='option_two',
        ),
    ]
