# Generated by Django 5.0.6 on 2024-06-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_option_3_questions_option_four_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='awnser',
            new_name='answer',
        ),
    ]
